### PR TITLE
Fix link

### PR DESCRIPTION
**Pull request by qm3ster**

### CODE REVIEW

**Comment by pi0** [comment]
Hi. Your help really appreciated. I think it would be better keeping all link consistent (Other items in features section are not links)

**Comment by qm3ster** [comment]
So.. do you want everything to be a link, or nothing to be a link? Which is it?
I only did this because there was a broken piece of markdown visible.

**Comment by pi0** [comment]
Yes, I know :) Now features section is plain text. What's your idea about current docs? Any change is appreciated if you want.

**Comment by qm3ster** [comment]
I am sure it's completely adequate. The table of contents is right there.

**Pull request closed without merging**
