### PR TITLE
Disable https for localhost url

### PR DESCRIPTION
**Pull request by yahtnif**

### CODE REVIEW

**Comment by vanekj** [comment]
Hi, why this change was made? I need to set HTTPS even for the localhost, now I know why my config `https: true` is not working after searching for a while.

**Comment by pi0** [comment]
@vanekj please open a PR

**Comment by vanekj** [comment]
Forget it, I achieved the wanted functionality by only setting the `baseURL` to `''` (empty string). Thank you, @pi0 🙂

**Comment by pi0** [comment]
@vanekj Your welcome and happy hearing your problem fixed.

**Comment by blowsie** [comment]
Im not sure why this have been implemented but it feels like a developer issue to me. 
What if someone wants to use https on localhost?

**Pull request merged**
