### PR TITLE
docs: migrate docs to nuxt/content

### PR DESCRIPTION
**Pull request by cogor**
What do you think about migrate to the nuxt/content and docs theme? 😅

[Preview link](https://axios-module-git-migrate-docs-to-nuxt-content.cogor.vercel.app)

### CODE REVIEW

**Comment by pi0** [comment]
Awesome @cogor. Would you please move content to `docs/` dir ?

**Comment by cogor** [comment]
> Awesome @cogor. Would you please move content to `docs/` dir ?

Yep

**Comment by pi0** [comment]
- To avoid unnecessary doc dependency install, we have a seperate package.json (https://github.com/nuxt-community/axios-module/blob/dev/docs/package.json) 
- It would be great if also `components` moved into `docs/` and markdowns `docs/contents`

Example: https://github.com/nuxt-community/pwa-module/tree/master/docs

**Comment by cogor** [comment]
> * To avoid unnecessary doc dependency install, we have a seperate package.json (https://github.com/nuxt-community/axios-module/blob/dev/docs/package.json)
> * It would be great if also `components` moved into `docs/` and markdowns `docs/contents`
> 
> Example: https://github.com/nuxt-community/pwa-module/tree/master/docs

Ok, I will try

**Comment by cogor** [comment]
I think now all is ok

**Comment by cogor** [comment]
@pi0 anything need from me? 🙂

**Comment by pi0** [comment]
Thanks for help @cogor 🙏 :100:

**Comment by pi0** [comment]
Docs released. PR Number is 404 :laughing:  /cc @debs-obrien if anything missing

**Comment by web2033** [comment]
@cogor bottom navigation for next/previous pages seems in the wrong order...

**Pull request merged**
