### PR TITLE
bump axios from 0.20.0 to 0.21.0

### LINKED ISSUE #419: $axios.$delete body payload is missing
`@nuxtjs/axios` version: 5.12.2

Issue:
When trying to call API on `delete` method, the request body is missing.

Example problematic code:
```
$axios.$delete('/store/products', {
    data: {
        [
            {
                sku: '1234',
            },
        ],
    },
}
```

More information:
`@nuxtjs/axios` 5.12.1 don't have this problem

### PR DESCRIPTION
**Pull request by suruaku**
Closes #419

### CODE REVIEW

**Comment by mathieutu** [comment]
@pi0 Could we merge and release this one? All delete calls are broken.

Thanks!

**Comment by sunecosuri** [comment]
@pi0 
Is there anything I can do to merge this?
Due to a Delete request glitch, I would like to see this change made public.

Thank you,

**Comment by simllll** [comment]
Even if it seems semver should cover this, the problem here is that axios is still an <1.0 release, therefore every minor is counted as "breaking change", and npm does not install 0.21 even when the dependecies is defined "axios": "^0.20.0".

Also looking forward to this be released! Having issues with weird typescript definitions as there are several versions of axios now in my node modules

**Comment by jakubm95** [comment]
@pi0 
When can we expect this update?

**Comment by pi0** [comment]
Merged by #410 and updated with v5.12.3

Sorry for delay. I didn't notice since indeed axios is not following semver for fixes (it had to be 0.20.1)

Also a tip: If using yarn, it is possible to use [resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) field to force update a dependency.

**Pull request closed without merging**
