### PR TITLE
docs: add typescript instructions

### PR DESCRIPTION
**Pull request by NickBolles**

### CODE REVIEW

**Comment by NickBolles** [comment]
@kevinmarrec huh. I tried that but it wasn't working for me. I was going to put that in the docs.

Any ideas why that wouldn't be working for me? I'll update the PR either way though.

**Comment by kevinmarrec** [comment]
@NickBolles Is it still not working ? I can take a look if you have reproduction repo

**Comment by NickBolles** [comment]
@kevinmarrec still not working on my laptop, but it's working on other computer. Something's probably just messed up with my laptop. 

Updated the instructions. Thank you!

**Comment by pi0** [comment]
Thanks @NickBolles @kevinmarrec ❤️

**Pull request merged**
